server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?serverTimezone=GMT&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    logging:
      level:
        com.yg: debug
      pattern:
        dateformat: MM-dd HH:mm:ss:SSS
mybatis:
  type-aliases-package:
  configuration:
    map-underscore-to-camel-case: true